import { Avatar } from "./types";

export const avatars: Avatar[] = [
  {
    id: "1",
    name: "Alya",
    role: "Warm & Friendly",
    type: "2D",
    language: "Bahasa Indonesia",
    voice: "id-ID-GadisNeural",
    image: "/avatars/alya-2d.jpg",
    specialty: "Skincare & Beauty",
  },
  {
    id: "2",
    name: "Luna",
    role: "Energetic Live Host",
    type: "3D",
    language: "Bahasa Indonesia",
    voice: "id-ID-SitiNeural",
    image: "/avatars/luna-3d.jpg",
    modelUrl3d: "/models/TufrillaVRM.vrm",
    specialty: "Hard-Selling TikTok Live",
  },
  {
    id: "3",
    name: "Cinta",
    role: "Professional & Elegant",
    type: "3D",
    language: "Bahasa Indonesia",
    voice: "id-ID-DahliaNeural",
    image: "/avatars/cinta-3d.jpg",
    modelUrl3d: "/models/brunette-realistic.glb",
    specialty: "Premium Branding & Fashion",
  },
  {
    id: "4",
    name: "Ardi",
    role: "Confident Tech Host",
    type: "2D",
    language: "Bahasa Indonesia",
    voice: "id-ID-ArdiNeural",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&q=80",
    specialty: "Gadget, Otomotif & Pria",
  },
  {
    id: "5",
    name: "Maya",
    role: "Modest Fashion Host",
    type: "2D",
    language: "Bahasa Indonesia",
    voice: "id-ID-GadisNeural",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&q=80",
    specialty: "Hijab & Muslimah Fashion",
  },
];
